{
 "title": "OPNSense Monitoring",
 "description": "Comprehensive monitoring dashboard designed for the OPNSense firewall/router operating system. It displays system and network metrics collected from Prometheus.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "opnsense_instance",
    "label": "OPNSense Instance",
    "query": {
     "query": "label_values(opnsense_arp_table_entries,opnsense_instance)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(opnsense_interfaces_received_bytes_total,interface)"
    }
   },
   {
    "name": "gateway",
    "label": "Gateway",
    "query": {
     "query": "label_values(opnsense_gateways_info,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds{instance=\"$opnsense_instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services Status History",
   "type": "status-history",
   "description": "Status points of services uptime\n\n1 - Available \n0 - Unavailable",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "opnsense_services_status{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (cpu) (\n  sum without (mode) (\n    rate(node_cpu_seconds_total{instance=\"$opnsense_instance\",mode!=\"idle\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without (cpu) (\n  sum without (mode) (\n    rate(node_cpu_seconds_total{instance=\"$opnsense_instance\",mode!=\"idle\"}[$__rate_interval])\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$opnsense_instance\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=\"$opnsense_instance\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=\"$opnsense_instance\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_active_bytes{instance=\"$opnsense_instance\"} + \nnode_memory_wired_bytes{instance=\"$opnsense_instance\"}) / \nnode_memory_size_bytes{instance=\"$opnsense_instance\"}) * 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_wired_bytes{instance=\"$opnsense_instance\"}",
     "legendFormat": "System Reserved Memory"
    },
    {
     "expr": "node_memory_active_bytes{instance=\"$opnsense_instance\"}",
     "legendFormat": "Active Memory"
    },
    {
     "expr": "node_zfs_arcstats_size_bytes{instance=\"$opnsense_instance\"}",
     "legendFormat": "File Cache (ZFS ARC)"
    },
    {
     "expr": "node_memory_inactive_bytes{instance=\"$opnsense_instance\"}",
     "legendFormat": "Inactive Memory"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_swap_used_bytes{instance=\"$opnsense_instance\"} / node_memory_swap_size_bytes{instance=\"$opnsense_instance\"}) * 100",
     "legendFormat": "Swap Usage"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_swap_used_bytes{instance=\"$opnsense_instance\"} / node_memory_swap_size_bytes{instance=\"$opnsense_instance\"})",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_exec_device_interrupts_total{instance=\"$opnsense_instance\"}[$__rate_interval])",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_exec_context_switches_total{instance=\"$opnsense_instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk & Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Filesystem Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$opnsense_instance\",mountpoint=\"/\"} - node_filesystem_free_bytes{instance=\"$opnsense_instance\",mountpoint=\"/\"}) / (node_filesystem_size_bytes{instance=\"$opnsense_instance\",mountpoint=\"/\"} - node_filesystem_free_bytes{instance=\"$opnsense_instance\",mountpoint=\"/\"} + node_filesystem_avail_bytes{instance=\"$opnsense_instance\",mountpoint=\"/\"}) * 100",
     "legendFormat": "/ usage"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_devstat_bytes_total{instance=\"$opnsense_instance\",type=\"read\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_devstat_bytes_total{instance=\"$opnsense_instance\",type=\"write\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(node_devstat_transfers_total{instance=\"$opnsense_instance\",type=\"read\"}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_devstat_transfers_total{instance=\"$opnsense_instance\",type=\"write\"}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "Gateway $gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }, "repeat": "gateway" },
  {
   "title": "Gateway Status",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (name) (opnsense_gateways_status{opnsense_instance=\"$opnsense_instance\",name=~\"$gateway\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Packet loss",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (name) (opnsense_gateways_loss_percentage{opnsense_instance=\"$opnsense_instance\",name=~\"$gateway\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RTT (latency)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (name) (opnsense_gateways_rtt_milliseconds{opnsense_instance=\"$opnsense_instance\",name=~\"$gateway\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Jitter (RTTd)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(opnsense_gateways_rttd_milliseconds{opnsense_instance=\"$opnsense_instance\",name=~\"$gateway\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "TCP Connection States",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opnsense_protocol_tcp_connection_count_by_state{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Received / Transmitted for  $interface",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "repeat": "interface",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(opnsense_interfaces_received_bytes_total{interface=~\"$interface\",opnsense_instance=\"$opnsense_instance\"}[$__rate_interval])",
     "legendFormat": "Received Bytes"
    },
    {
     "expr": "-rate(opnsense_interfaces_transmitted_bytes_total{interface=~\"$interface\",opnsense_instance=\"$opnsense_instance\"}[$__rate_interval])",
     "legendFormat": "Transmitted Bytes"
    }
   ]
  },
  { "title": "Firewall Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Firewall Statistics by Interface",
   "type": "table",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum by (interface) (opnsense_firewall_in_ipv4_pass_packets{opnsense_instance=\"$opnsense_instance\",interface=~\"igb.*\"}) / ((sum by (interface) (opnsense_firewall_in_ipv4_pass_packets{opnsense_instance=\"$opnsense_instance\",interface=~\"igb.*\"}) + sum by (interface) (opnsense_firewall_in_ipv4_block_packets{opnsense_instance=\"$opnsense_instance\",interface=~\"igb.*\"})) > 0) * 100",
     "legendFormat": "Passed %"
    },
    {
     "expr": "sum by (interface) (opnsense_firewall_in_ipv4_block_packets{opnsense_instance=\"$opnsense_instance\",interface=~\"igb.*\"}) / ((sum by (interface) (opnsense_firewall_in_ipv4_pass_packets{opnsense_instance=\"$opnsense_instance\",interface=~\"igb.*\"}) + sum by (interface) (opnsense_firewall_in_ipv4_block_packets{opnsense_instance=\"$opnsense_instance\",interface=~\"igb.*\"})) > 0) * 100",
     "legendFormat": "Blocked %"
    },
    {
     "expr": "sum by (interface) (opnsense_firewall_in_ipv4_pass_packets{opnsense_instance=\"$opnsense_instance\",interface=~\"igb.*\"})",
     "legendFormat": "Passed"
    },
    {
     "expr": "sum by (interface) (opnsense_firewall_in_ipv4_block_packets{opnsense_instance=\"$opnsense_instance\",interface=~\"igb.*\"})",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Firewall IPv4 Traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(opnsense_firewall_in_ipv4_pass_packets{opnsense_instance=\"$opnsense_instance\"}[$__rate_interval]))",
     "legendFormat": "In Pass"
    },
    {
     "expr": "sum(rate(opnsense_firewall_in_ipv4_block_packets{opnsense_instance=\"$opnsense_instance\"}[$__rate_interval]))",
     "legendFormat": "In Block"
    },
    {
     "expr": "sum(rate(opnsense_firewall_out_ipv4_pass_packets{opnsense_instance=\"$opnsense_instance\"}[$__rate_interval]))",
     "legendFormat": "Out Pass"
    },
    {
     "expr": "sum(rate(opnsense_firewall_out_ipv4_block_packets{opnsense_instance=\"$opnsense_instance\"}[$__rate_interval]))",
     "legendFormat": "Out Block"
    }
   ]
  },
  {
   "title": "Input Errors",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 55, "w": 8, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(opnsense_interfaces_input_errors_total{interface=~\"$interface\",opnsense_instance=\"$opnsense_instance\"}[$__rate_interval])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Output Errors",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 55, "w": 8, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(opnsense_interfaces_output_errors_total{interface=~\"$interface\",opnsense_instance=\"$opnsense_instance\"}[$__rate_interval])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Collisions",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 55, "w": 8, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(opnsense_interfaces_collisions_total{interface=~\"$interface\",opnsense_instance=\"$opnsense_instance\"}[$__rate_interval])",
     "legendFormat": "{{interface}}"
    }
   ]
  }
 ]
}