{
 "title": "rclone",
 "tags": [ "rclone" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "ligma : http://127.0.0.1:6969,storma : http://10.10.10.12:6969"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "type": "json",
     "source": "url",
     "url": "${instance}/core/stats",
     "url_options": { "method": "POST", "data": "" },
     "columns": [
      { "selector": "speed", "text": "speed", "type": "number" }
     ],
     "parser": "backend"
    }
   ]
  },
  {
   "title": "Bytes This Run",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "type": "json",
     "source": "url",
     "url": "${instance}/core/stats",
     "url_options": { "method": "POST", "data": "" },
     "columns": [
      { "selector": "bytes", "text": "bytes", "type": "number" }
     ],
     "parser": "backend"
    }
   ]
  },
  {
   "title": "Active Transfers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "type": "json",
     "source": "url",
     "url": "${instance}/core/stats",
     "url_options": { "method": "POST", "data": "" },
     "root_selector": "transferring[*]",
     "columns": [
      { "selector": "name", "text": "name", "type": "string" }
     ],
     "parser": "backend"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"rclone\", instance=~\"${instance:text}\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Status Totals",
   "type": "piechart",
   "description": "Since rclone process started",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rclone_checked_files_total{job=\"rclone\", instance=~\"${instance:text}\"}",
     "legendFormat": "Checked files"
    },
    {
     "expr": "rclone_files_transferred_total{job=\"rclone\", instance=~\"${instance:text}\"}",
     "legendFormat": "Transferred files"
    },
    {
     "expr": "rclone_files_renamed_total{job=\"rclone\", instance=~\"${instance:text}\"}",
     "legendFormat": "Renamed files"
    },
    {
     "expr": "rclone_files_deleted_total{job=\"rclone\", instance=~\"${instance:text}\"}",
     "legendFormat": "Deleted files"
    },
    {
     "expr": "rclone_dirs_deleted_total{job=\"rclone\", instance=~\"${instance:text}\"}",
     "legendFormat": "Deleted directories"
    },
    {
     "expr": "rclone_errors_total{job=\"rclone\", instance=~\"${instance:text}\"}",
     "legendFormat": "Transfer errors"
    }
   ]
  },
  {
   "title": "Requests by Response Code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{job=\"rclone\", instance=~\"${instance:text}\"}",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Current Transfers",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "type": "json",
     "source": "url",
     "url": "${instance}/core/stats",
     "url_options": { "method": "POST", "data": "" },
     "root_selector": "transferring[*]",
     "columns": [
      { "selector": "name", "text": "name", "type": "string" },
      { "selector": "size", "text": "size", "type": "number" },
      { "selector": "bytes", "text": "bytes", "type": "number" },
      { "selector": "speed", "text": "speed", "type": "number" },
      { "selector": "percentage", "text": "percentage", "type": "number" },
      { "selector": "eta", "text": "eta", "type": "number" }
     ],
     "parser": "backend"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(rclone_bytes_transferred_total{job=\"rclone\", instance=~\"${instance:text}\"}[$__rate_interval])",
     "legendFormat": "Transfer rate"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"rclone\", instance=~\"${instance:text}\"}",
     "legendFormat": "Open file descriptors"
    },
    {
     "expr": "process_max_fds{job=\"rclone\", instance=~\"${instance:text}\"}",
     "legendFormat": "Max open file descriptors"
    }
   ]
  },
  {
   "title": "Files Transferred",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(rclone_files_transferred_total{job=\"rclone\", instance=~\"${instance:text}\"}[$__rate_interval])",
     "legendFormat": "Files transferred"
    },
    {
     "expr": "increase(rclone_files_deleted_on_destination_total{job=\"rclone\", instance=~\"${instance:text}\"}[$__rate_interval])",
     "legendFormat": "Files deleted (dst)"
    }
   ]
  },
  { "title": "VFS Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Cached Objects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(\n  {job=\"${instance:text}-syslog\", unit=\"rclone-cloud.service\"} |= \"vfs cache: cleaned\"\n  | regexp `objects (?P<val>\\d+) \\(was`\n  | unwrap val [$__range]\n)"
    }
   ]
  },
  {
   "title": "In Use",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(\n  {job=\"${instance:text}-syslog\", unit=\"rclone-cloud.service\"} |= \"vfs cache: cleaned\"\n  | regexp `in use (?P<val>\\d+),`\n  | unwrap val [$__range]\n)"
    }
   ]
  },
  {
   "title": "To Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(\n  {job=\"${instance:text}-syslog\", unit=\"rclone-cloud.service\"} |= \"vfs cache: cleaned\"\n  | regexp `to upload (?P<val>\\d+),`\n  | unwrap val [$__range]\n)"
    }
   ]
  },
  {
   "title": "Uploading",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(\n  {job=\"${instance:text}-syslog\", unit=\"rclone-cloud.service\"} |= \"vfs cache: cleaned\"\n  | regexp `uploading (?P<val>\\d+),`\n  | unwrap val [$__range]\n)"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(\n  {job=\"${instance:text}-syslog\", unit=\"rclone-cloud.service\"} |= \"vfs cache: cleaned\"\n  | regexp `total size (?P<val>[\\d.]+)Gi`\n  | unwrap val [$__range]\n)"
    }
   ]
  },
  {
   "title": "VFS Cache Objects",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(\n  {job=\"${instance:text}-syslog\", unit=\"rclone-cloud.service\"} |= \"vfs cache: cleaned\"\n  | regexp `objects (?P<val>\\d+) \\(was`\n  | unwrap val [$__interval]\n)",
     "legendFormat": "objects"
    },
    {
     "expr": "last_over_time(\n  {job=\"${instance:text}-syslog\", unit=\"rclone-cloud.service\"} |= \"vfs cache: cleaned\"\n  | regexp `in use (?P<val>\\d+),`\n  | unwrap val [$__interval]\n)",
     "legendFormat": "in use"
    },
    {
     "expr": "last_over_time(\n  {job=\"${instance:text}-syslog\", unit=\"rclone-cloud.service\"} |= \"vfs cache: cleaned\"\n  | regexp `to upload (?P<val>\\d+),`\n  | unwrap val [$__interval]\n)",
     "legendFormat": "to upload"
    },
    {
     "expr": "last_over_time(\n  {job=\"${instance:text}-syslog\", unit=\"rclone-cloud.service\"} |= \"vfs cache: cleaned\"\n  | regexp `uploading (?P<val>\\d+),`\n  | unwrap val [$__interval]\n)",
     "legendFormat": "uploading"
    }
   ]
  },
  {
   "title": "VFS Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "last_over_time(\n  {job=\"${instance:text}-syslog\", unit=\"rclone-cloud.service\"} |= \"vfs cache: cleaned\"\n  | regexp `total size (?P<val>[\\d.]+)Gi`\n  | unwrap val [$__interval]\n)",
     "legendFormat": "size GiB"
    }
   ]
  },
  {
   "title": "rclone Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "{job=\"${instance:text}-syslog\", unit=\"rclone-cloud.service\"}"
    }
   ]
  }
 ]
}