{
 "title": "Rclone Metrics",
 "description": "Dashboard for Rclone rc metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Rclone",
    "query": {
     "query": "label_values(rclone_bytes_transferred_total, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Rclone running since",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=~\"$instance\"} * 1000",
     "legendFormat": "Start time"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "process_open_fds"
    }
   ]
  },
  {
   "title": "Status Totals",
   "type": "piechart",
   "description": "Since rclone process started",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rclone_checked_files_total{instance=~\"$instance\"}",
     "legendFormat": "Checked files"
    },
    {
     "expr": "rclone_files_transferred_total{instance=~\"$instance\"}",
     "legendFormat": "Transferred files"
    },
    {
     "expr": "rclone_files_renamed_total{instance=~\"$instance\"}",
     "legendFormat": "Renamed files"
    },
    {
     "expr": "rclone_files_deleted_total{instance=~\"$instance\"}",
     "legendFormat": "Deleted files"
    },
    {
     "expr": "rclone_dirs_deleted_total{instance=~\"$instance\"}",
     "legendFormat": "Deleted directories"
    },
    {
     "expr": "rclone_errors_total{instance=~\"$instance\"}",
     "legendFormat": "Transfer errors"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "Open file descriptors"
    },
    {
     "expr": "process_max_fds{instance=~\"$instance\"}",
     "legendFormat": "Max open file descriptors"
    }
   ]
  },
  {
   "title": "/metrcs - Requests by response code",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{instance=~\"$instance\"}",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Total Data Transferred",
   "type": "stat",
   "description": "Since rclone process started",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rclone_bytes_transferred_total{instance=~\"$instance\"}",
     "legendFormat": "Total bytes transferred"
    }
   ]
  },
  {
   "title": "Average Speed",
   "type": "stat",
   "description": "Since rclone process started",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rclone_speed{instance=~\"$instance\"}",
     "legendFormat": "rclone_speed"
    }
   ]
  },
  {
   "title": "Status per action",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(rclone_checked_files_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Checked files"
    },
    {
     "expr": "increase(rclone_files_transferred_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Transferred files"
    },
    {
     "expr": "increase(rclone_files_renamed_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Renamed files"
    },
    {
     "expr": "increase(rclone_files_deleted_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Deleted files"
    },
    {
     "expr": "increase(rclone_dirs_deleted_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Deleted directories"
    },
    {
     "expr": "increase(rclone_errors_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Transfer errors"
    }
   ]
  },
  {
   "title": "Data Transferred",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rclone_bytes_transferred_total{instance=~\"$instance\"}",
     "legendFormat": "Total data transferred"
    }
   ]
  },
  {
   "title": "Data Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(rclone_bytes_transferred_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Data transfer rate"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "Go threads"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU seconds"
    }
   ]
  },
  {
   "title": "Go Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "Allocated bytes"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "Coroutines"
    }
   ]
  },
  {
   "title": "Go Heap Objects",
   "type": "timeseries",
   "description": "Total number of allocated objects",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{instance=~\"$instance\"}",
     "legendFormat": "Objects"
    }
   ]
  },
  {
   "title": "Go Heap Memory Overview",
   "type": "timeseries",
   "description": "**Allocated:** The amount of memory Rclone is actually using.  \n**Sys:** The amount of memory obtained from the OS.  \n**Sys requested:** The amount of memory requested from the OS.",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "Sys requested bytes"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "Allocated bytes"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "Sys bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=~\"$instance\"}",
     "legendFormat": "Idle bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "In use bytes"
    },
    {
     "expr": "go_memstats_heap_released_bytes{instance=~\"$instance\"}",
     "legendFormat": "Released bytes"
    }
   ]
  }
 ]
}